name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y ros-humble-ament-cmake
          rosdep update
          rosdep install --from-paths ~/ros2_ws/src --ignore-src -r -y

      - uses: actions/checkout@v2
      - name: build and test
        run: |
          rsync -av ./ root/ros2_ws/src/ros2_homework/
          cd /root/ros2_ws
          bash -xv ./src/ros2_homework/test/test.bash /root    
